### ISSUE TITLE
Allow Infecteds to "smell" invisible players

### ISSUE THREAD

**Issue by Laifsyn** [jedijoe93/ImmortuosCalyx#11]
So, just as the title, would be kinda spooky if the infecteds are able to stare at you while invisible(Specifically with no armor visible[Worded this way because there's an outdate mod for 1.17 that allows you to at least visually hide your armor])

**Comment by CartoonishVillain** [comment]
Thank you for the suggestion!

Unfortunately I do not believe that I will move forward with this suggestion at this time. While the parasite is smart enough to attempt to spread itself, they do not convert their hosts into ruthless hunters, but instead husks of their former selves that they sometimes struggle to control.

Though in a future patch, **possibly** there could be some entity that does track like this. But it's a bit iffy as it's far from and kind of out of the spirit of the source material.
