### ISSUE TITLE
[1.18.2] Crash in BYG biome at 85% infection.

### ISSUE THREAD

**Issue by Baggytrousers27** [jedijoe93/ImmortuosCalyx#13]
The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: 'net.minecraft.world.level.biome.Biome net.minecraft.world.level.biome.BiomeManager.m_47881_(net.minecraft.core.BlockPos)'
Exit Code: -1

immortuoscalyx-1.18-1.6.4
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-11-all
TerraBlender-forge-1.18.2-1.1.0.98

Seed used: 4935950446636565443

[Crashlog](https://pastebin.com/8C5PgRBn)

Edit: Nevermind. Found the level.dat infection thingy.

**Comment by CartoonishVillain** [comment]
Ah I see the problem. I made a patch for the new biome changes a little while ago but somehow forgot about it and called the old 1.18 build 1.18.2 ready. My apologies for the inconvenience! I'll have the patch out tonight. Will close issue when it's uploaded

**Comment by Baggytrousers27** [comment]
Cheers and thanking you muchly. ¦D

**Comment by CartoonishVillain** [comment]
It appears for one reason or another, the patch may be under manual review (or curseforge is slow)

In either case, it's availability will be delayed. I'll make a GitHub release for it later
