### ISSUE TITLE
[suggestion] players leave behind an infected player when they die of other causes after a certain threshold

### ISSUE THREAD

**Issue by lag42** [jedijoe93/ImmortuosCalyx#5]
a common strategy on a server i help run has become to die of fall damage before the infection can get to 100%

i would like to put just a slight downside to this in the form of making it leave behind an infected player anyways after it passes a certain percentage even if that's not 100% accurate to barotrauma

**Comment by CartoonishVillain** [comment]
A good idea. I'll likely introduce this feature as a configurable option. Debating on whether or not it'll be on by default or not at the moment

**Comment by CartoonishVillain** [comment]
This was implemented! By default, for every % above 50 an entity is infected, 2% chance is added that they will be replaced on death with an infected form outside of death by obliteration (void, explosions, lava, etc)
