### ISSUE TITLE
Infinite Iron Golems

### ISSUE THREAD

**Issue by Laifsyn** [jedijoe93/ImmortuosCalyx#7]
I don't know if intended, but once there's an infected Iron Golem, you can't kill it unless you use extreme methods, It will respawn another iron Golem. I even had once where I chomped an infected iron golem like 7 times, and he was still respawning more until I pushed him into a hole, and threw some lava in

**Comment by CartoonishVillain** [comment]
Well that sure is peculiar. Mod version, game version, and launcher please?

**Comment by Laifsyn** [comment]
follow up - I think they actually perma respawn. Extreme methods does seems to kill it for all though

**Comment by Laifsyn** [comment]
Mod Version: immortuoscalyx-1.2.2-1.18.jar
Fabric Version: 0.10.2(I'm not sure how to check it the actual version, but this was the version of the installer I've used)
Launcher: SKLauncher

**Comment by CartoonishVillain** [comment]
Ah, I think I have an idea of what's wrong, please hold

**Comment by CartoonishVillain** [comment]
Ah I see. In a recent update I added a way for partially infected entities to become fully infected during death. I forgot to add a check to ensure that these infected mobs do not do this as well. Quite embarassing. Disabling this option in the config for now should solve your issue, an update will come out shortly also resolving this issue without needing to change configs. This ticket will close when the update releases. Thank you for reporting!

**Comment by Laifsyn** [comment]
Alright. No problem. That's a really interesting and scary bug. Believing you are almost done, just to see Part 2 and Part Infinite

**Comment by Laifsyn** [comment]
Oh. Another, possibly hard to replicate on normal conditions and track/sniff out bug.

The golem may randomly attack an converted player(At least spawned from the egg it seems)
https://imgur.com/a/Pqqdm9K

**Comment by Laifsyn** [comment]
Forgot to say, I also have couple mods that affect(with the objective to optimize) NPC behaviours not sure if it would affect in some way

**Comment by CartoonishVillain** [comment]
It may be the case, especially if it modifies the goals of Iron golems at all. Since I do use vanilla iron golems as the base for this entity
