### ISSUE TITLE
Not losing HP after threshold

### ISSUE THREAD

**Issue by Laifsyn** [jedijoe93/ImmortuosCalyx#8]
Same guy from the Iron golem. I have registered 100+ infection, and I'm not losing HP.  (even with the defaults values)
![image](https://user-images.githubusercontent.com/99366187/153327570-95f5174f-c877-4801-becc-4e772cbae9dc.png)

**Comment by CartoonishVillain** [comment]
Unable to reproduce. Suspect that other config values are in play that could mess it up. Though it isn't a constant stream of damage (random chance every tick)

**Comment by CartoonishVillain** [comment]
Please send a copy of the server's config (or your config if singleplayer). Besides potential mod conflicts, it's the only idea I have about this issue.

**Comment by Laifsyn** [comment]
[Immortuos Current Config.txt](https://github.com/CartoonishVillain/ImmortuosCalyx/files/8044642/Immortuos.Current.Config.txt)
My current Server Config

![about just after Immortuos Eggs](https://user-images.githubusercontent.com/99366187/153504531-fbba9f49-9110-48c9-bbd7-d8dd47b169c5.png)
![at 180+ infection](https://user-images.githubusercontent.com/99366187/153504539-9963e320-17fa-4d6b-8bfc-8c18aef1118c.png)

Also, apparently the egg inject doesn't work.
Percent increase was left to 1% per sec. 

I also have "Villainous Difficulty Multipliers" installed, idk if it affects.
Mod Lists in my server(if it matters): https://pastebin.com/LbenHe5G

**Comment by Laifsyn** [comment]
I made sure to be away from the campfire, so as to not trigger the campfire effect

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/153506635-6aaeb7e9-ec86-446e-bb62-28c245b331b6.png)
Villager doesn't react with the infected

**Comment by CartoonishVillain** [comment]
VDM does have a multipliers does have a tie in to Immortuos, but this shouldn't effect infections like this. 

Eggs will simply infect people to configured amount. They will be wasted if the user is already above that configured amount. 

Villagers, in most cases, shouldn't attack entities that are already infected, due to their generally peaceful status in life. 

Config file looks clean. Very strange. If I had to guess it's being canceled by some other mod. Wouldn't know what though.

**Comment by Laifsyn** [comment]
For the eggs one, I've set it to 100, so I could jump from 0 to 100 instantly.

**Comment by Laifsyn** [comment]
Suggestion - A Config option which edits how common the dmg tick happens when over the dmg threshold.

Update on my attempts: I've reduced the mod list to 
```
(1) autoconfig1u-3.3.1.jar
(2) cardinal-components-api-4.1.2.jar
(3) cloth-config-6.2.57-fabric.jar
(4) immortuoscalyx-1.2.2-1.18.jar
(5) jei-1.18.1-9.2.3.84.jar
(6) recipecache-0.2.1-1.17.1.jar
(7) starlight-1.0.1+fabric.0583973.jar
```
And I haven't seen any dmg tick so far(about 2 mins into the game already

**Comment by CartoonishVillain** [comment]
Very strange. I'll need to make a debug config to add optional log printouts. If it still isn't working with that, but does on my device, then something has gone terribly wrong. I do apologize for the inconvenience. I'll try to come up with such a build before all too long

**Comment by Laifsyn** [comment]
Maybe a Fluke data corruption? I haven't attempted to reinstall from scratch yet though

**Comment by Laifsyn** [comment]
But I can't afford to play from scratch because.. Progress and mods configs ¯\_(ツ)_/¯

**Comment by CartoonishVillain** [comment]
All good. Possible it was a fluke, but unlikely. In any case I'll still be making a test build just to see if I can figure it out. If not, I suppose I can close the ticket for now and wait until it pops up again. I am still however planning on making a debug config that gives more info for these sorts of. Absolutely bizarre occurrences.

**Comment by Laifsyn** [comment]
Definitely

**Comment by Laifsyn** [comment]
A Install from scratch did help. I was receiving some ocassional dmg ticks once over the threshold. After running the backup, I emptied the mods but the ones related to Immortuous, Cleared the Config Folder, and some other folders that were clearly from some mods that are in the World folder.
I guess I can only wait for the debug release so as to continue this thread

**Comment by CartoonishVillain** [comment]
Occasional damage is about what I was aiming for. Something I was curious about, did these issues occur before you installed the update for the previous bug? If not then it really does just sound like an absolute fluke.

If this is the case, I recommend backing up your world, deleting that copy of immortuos, moving the new one in, and maybe moving the config out for good measure. Then update a freshly generated config to have the values you originally wanted. If this truly was a fluke, this should fix it without any issues to your world. Of course this is not a guarantee, and you should always have a backup before you try anything like this.

**Comment by Laifsyn** [comment]
On the first server run with the mod, I was with a friend all running around the world trying to get the mats for the anti-parasitic serum because we thought we would insta die once we reached the 100 threshold. Well, it was kinda anticlimatic with nothing happening but half black screen. Now that I mention this, it would be interesting to allow "insta death" but pure suggestion anyways.

So we could say it happened since the install

**Comment by CartoonishVillain** [comment]
If you want instant death, you can config it to happen. You only need to set INFECTIONDAMAGE to a higher value. 20 should instantly kill the average player, but something much higher would ensure death.

In the future though, to make the mod closer to the source material, I do plan on bumping up the config by default. I'm still playing with the numbers to get what feels right. Trying to strike the right balance between dramatic death while also giving even the slimmest of chances to get a heal of some kind off.

**Comment by Laifsyn** [comment]
Oh, Is there a way to edit the msg prompts? I was thinking about - like just when they get blind or reach the dmg threshold send an extra message saying "The Parasite is rampaging over and trying to take over your body - Store your stuff so you can retrieve it later!" so to give them a small clear-headedness moement before they lose any material progress

**Comment by CartoonishVillain** [comment]
At this time no, may be possible through resource packs later when I convert the messages to translatable components instead of the current hardcoded method though. Would just need to overtake an existing message.

**Comment by Laifsyn** [comment]
I see. Oh, well. About the dmg bug. I've tested things. AND.... For some strange reason I only received dmg when I ran the server with 
		// Changes when players will start being damaged by the parasite
		"EFFECTDAMAGE": 5,
Not sure if it was because of reinstall or because of that though, but most likely because of that, since re-running the server with EffectDamage:5 I started to get dmg

Edit: Maybe I actually just didn't see the infected player

**Comment by Laifsyn** [comment]
Gonna test it with 10 though

**Comment by CartoonishVillain** [comment]
That's real odd. That setting controls when the user starts getting harmed

**Comment by Laifsyn** [comment]
Alright, maybe I indeed forgot about the infected player( I didn't disable blind). As for Single player I do get dmg tick though. So Either server Hosting issues, or due to a server side, gonna run a couple tests first before anything

**Comment by Laifsyn** [comment]
Results: Nothing useful - I give up.
More details: 

- Hosting Server: Aternos
- Fabric 1.18.1 (0.13.1)

_Steps: While Runing(Delete Mod and Config Folder) > Stop Server > Start Server 
> Stop Server > Install Immortuos and related > Start server to create config files
> Stop Server > Edit Config > Start Server > Log into the Server

Test 2: Same as above, but I also loaded my player in between every server start._

I might come back if there's debug configs so I open another ticket if there's any info you would like for me to send

**Comment by CartoonishVillain** [comment]
I think for now I will probably close out the ticket. I don't have the time to commit to a debug build at the moment, but over the weekend I should have a bit more (Maybe tomorrow). It sounds like maybe something is just being weird with damage, whether it's another mod or that particular install of immortuos, as I can't get the same issues to occur. When the debug update does come out, if the issue persists after updating, if you would like to start another issue (or reopen this one) with a log of the damage trying to run for a while, that'd be pretty neat though. Thank you for your time and for reporting!
