### ISSUE TITLE
Does Shield Block Infection?

### ISSUE THREAD

**Issue by Laifsyn** [jedijoe93/ImmortuosCalyx#9]
Will it still transfer infection even if you succesfully block an attack with a shield? or you've programmed it so to only trigger when damaged?

**Comment by Laifsyn** [comment]
Asking because I have a Shield mods, and it would be really awkward to still get infected even through a Netherite Shield

**Comment by CartoonishVillain** [comment]
Maybe? It would really be a case by case basis on how each different instance handles their code. There is no solid answer to be had outside of testing each case.

It probably shouldn't on vanilla shields, but frankly, I haven't tried and it isn't that big of a deal if it does.
